# 已在nacos配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.16.30.198:6006/sms_platform?characterEncoding=utf-8&useSSL=false
#    password: lpp6006ROOT
#    username: root
#    type: com.alibaba.druid.pool.DruidDataSource
#server:
#  port: 18089
#
#shiro:
#  loginUrl: /login.html
#  unauthorizedUrl: /unauthorized.html
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true